/*  =========================================================================
    mal - generated layer of public API

    The MIT License (MIT)
    Copyright (c) 2016 CNES

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef MAL_LIBRARY_H_INCLUDED
#define MAL_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <clog.h>
#include <malattributes.h>

//  MAL version macros for compile-time API detection
#define MAL_VERSION_MAJOR 1
#define MAL_VERSION_MINOR 2
#define MAL_VERSION_PATCH 0

#define MAL_MAKE_VERSION(major, minor, patch)                                  \
  ((major)*10000 + (minor)*100 + (patch))
#define MAL_VERSION                                                            \
  MAL_MAKE_VERSION(MAL_VERSION_MAJOR, MAL_VERSION_MINOR, MAL_VERSION_PATCH)

// czmq_prelude.h bits
#if !defined(__WINDOWS__)
#if (defined WIN32 || defined _WIN32 || defined WINDOWS || defined _WINDOWS)
#undef __WINDOWS__
#define __WINDOWS__
#endif
#endif

// Windows MSVS doesn't have stdbool
#if (defined(_MSC_VER) && !defined(true))
#if (!defined(__cplusplus) && (!defined(true)))
#define true 1
#define false 0
typedef char bool;
#endif
#else
#include <stdbool.h>
#endif
// czmq_prelude.h bits

#if defined(__WINDOWS__)
#if defined MAL_STATIC
#define MAL_EXPORT
#elif defined MAL_INTERNAL_BUILD
#if defined DLL_EXPORT
#define MAL_EXPORT __declspec(dllexport)
#else
#define MAL_EXPORT
#endif
#elif defined MAL_EXPORTS
#define MAL_EXPORT __declspec(dllexport)
#else
#define MAL_EXPORT __declspec(dllimport)
#endif
#define MAL_PRIVATE
#elif defined(__CYGWIN__)
#define MAL_EXPORT
#define MAL_PRIVATE
#else
#if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#define MAL_PRIVATE __attribute__((visibility("hidden")))
#define MAL_EXPORT __attribute__((visibility("default")))
#else
#define MAL_PRIVATE
#define MAL_EXPORT
#endif
#endif

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
typedef struct _mal_ctx_t mal_ctx_t;
#define MAL_CTX_T_DEFINED
typedef struct _mal_routing_t mal_routing_t;
#define MAL_ROUTING_T_DEFINED
typedef struct _mal_endpoint_t mal_endpoint_t;
#define MAL_ENDPOINT_T_DEFINED
typedef struct _mal_poller_t mal_poller_t;
#define MAL_POLLER_T_DEFINED
typedef struct _mal_integer_list_t mal_integer_list_t;
#define MAL_INTEGER_LIST_T_DEFINED
typedef struct _mal_uinteger_list_t mal_uinteger_list_t;
#define MAL_UINTEGER_LIST_T_DEFINED
typedef struct _mal_double_list_t mal_double_list_t;
#define MAL_DOUBLE_LIST_T_DEFINED
typedef struct _mal_float_list_t mal_float_list_t;
#define MAL_FLOAT_LIST_T_DEFINED
typedef struct _mal_long_list_t mal_long_list_t;
#define MAL_LONG_LIST_T_DEFINED
typedef struct _mal_ulong_list_t mal_ulong_list_t;
#define MAL_ULONG_LIST_T_DEFINED
typedef struct _mal_short_list_t mal_short_list_t;
#define MAL_SHORT_LIST_T_DEFINED
typedef struct _mal_ushort_list_t mal_ushort_list_t;
#define MAL_USHORT_LIST_T_DEFINED
typedef struct _mal_octet_list_t mal_octet_list_t;
#define MAL_OCTET_LIST_T_DEFINED
typedef struct _mal_uoctet_list_t mal_uoctet_list_t;
#define MAL_UOCTET_LIST_T_DEFINED
typedef struct _mal_boolean_list_t mal_boolean_list_t;
#define MAL_BOOLEAN_LIST_T_DEFINED
typedef struct _mal_string_list_t mal_string_list_t;
#define MAL_STRING_LIST_T_DEFINED
typedef struct _mal_blob_list_t mal_blob_list_t;
#define MAL_BLOB_LIST_T_DEFINED
typedef struct _mal_time_list_t mal_time_list_t;
#define MAL_TIME_LIST_T_DEFINED
typedef struct _mal_finetime_list_t mal_finetime_list_t;
#define MAL_FINETIME_LIST_T_DEFINED
typedef struct _mal_duration_list_t mal_duration_list_t;
#define MAL_DURATION_LIST_T_DEFINED
typedef struct _mal_uri_list_t mal_uri_list_t;
#define MAL_URI_LIST_T_DEFINED
typedef struct _mal_interactiontype_list_t mal_interactiontype_list_t;
#define MAL_INTERACTIONTYPE_LIST_T_DEFINED
typedef struct _mal_identifier_list_t mal_identifier_list_t;
#define MAL_IDENTIFIER_LIST_T_DEFINED
typedef struct _mal_message_t mal_message_t;
#define MAL_MESSAGE_T_DEFINED
typedef struct _mal_entitykey_t mal_entitykey_t;
#define MAL_ENTITYKEY_T_DEFINED
typedef struct _mal_entitykey_list_t mal_entitykey_list_t;
#define MAL_ENTITYKEY_LIST_T_DEFINED
typedef struct _mal_entityrequest_t mal_entityrequest_t;
#define MAL_ENTITYREQUEST_T_DEFINED
typedef struct _mal_entityrequest_list_t mal_entityrequest_list_t;
#define MAL_ENTITYREQUEST_LIST_T_DEFINED
typedef struct _mal_updateheader_t mal_updateheader_t;
#define MAL_UPDATEHEADER_T_DEFINED
typedef struct _mal_updateheader_list_t mal_updateheader_list_t;
#define MAL_UPDATEHEADER_LIST_T_DEFINED
typedef struct _mal_subscription_t mal_subscription_t;
#define MAL_SUBSCRIPTION_T_DEFINED
typedef struct _mal_subscription_list_t mal_subscription_list_t;
#define MAL_SUBSCRIPTION_LIST_T_DEFINED
typedef struct _mal_element_holder_t mal_element_holder_t;
#define MAL_ELEMENT_HOLDER_T_DEFINED
typedef struct _mal_file_t mal_file_t;
#define MAL_FILE_T_DEFINED
typedef struct _mal_file_list_t mal_file_list_t;
#define MAL_FILE_LIST_T_DEFINED
typedef struct _mal_idbooleanpair_t mal_idbooleanpair_t;
#define MAL_IDBOOLEANPAIR_T_DEFINED
typedef struct _mal_idbooleanpair_list_t mal_idbooleanpair_list_t;
#define MAL_IDBOOLEANPAIR_LIST_T_DEFINED
typedef struct _mal_namedvalue_t mal_namedvalue_t;
#define MAL_NAMEDVALUE_T_DEFINED
typedef struct _mal_namedvalue_list_t mal_namedvalue_list_t;
#define MAL_NAMEDVALUE_LIST_T_DEFINED
typedef struct _mal_pair_t mal_pair_t;
#define MAL_PAIR_T_DEFINED
typedef struct _mal_pair_list_t mal_pair_list_t;
#define MAL_PAIR_LIST_T_DEFINED
typedef struct _mal_sessiontype_list_t mal_sessiontype_list_t;
#define MAL_SESSIONTYPE_LIST_T_DEFINED
typedef struct _mal_updatetype_list_t mal_updatetype_list_t;
#define MAL_UPDATETYPE_LIST_T_DEFINED
typedef struct _mal_qoslevel_list_t mal_qoslevel_list_t;
#define MAL_QOSLEVEL_LIST_T_DEFINED
typedef struct _mal_encoder_t mal_encoder_t;
#define MAL_ENCODER_T_DEFINED
typedef struct _mal_decoder_t mal_decoder_t;
#define MAL_DECODER_T_DEFINED
typedef struct _mal_t mal_t;
#define MAL_T_DEFINED

//  Public classes, each with its own header file
#include "mal_blob_list.h"
#include "mal_boolean_list.h"
#include "mal_ctx.h"
#include "mal_decoder.h"
#include "mal_double_list.h"
#include "mal_duration_list.h"
#include "mal_element_holder.h"
#include "mal_encoder.h"
#include "mal_endpoint.h"
#include "mal_entitykey.h"
#include "mal_entitykey_list.h"
#include "mal_entityrequest.h"
#include "mal_entityrequest_list.h"
#include "mal_file.h"
#include "mal_file_list.h"
#include "mal_finetime_list.h"
#include "mal_float_list.h"
#include "mal_idbooleanpair.h"
#include "mal_idbooleanpair_list.h"
#include "mal_identifier_list.h"
#include "mal_integer_list.h"
#include "mal_interactiontype_list.h"
#include "mal_long_list.h"
#include "mal_message.h"
#include "mal_namedvalue.h"
#include "mal_namedvalue_list.h"
#include "mal_octet_list.h"
#include "mal_pair.h"
#include "mal_pair_list.h"
#include "mal_poller.h"
#include "mal_qoslevel_list.h"
#include "mal_routing.h"
#include "mal_sessiontype_list.h"
#include "mal_short_list.h"
#include "mal_string_list.h"
#include "mal_subscription.h"
#include "mal_subscription_list.h"
#include "mal_time_list.h"
#include "mal_uinteger_list.h"
#include "mal_ulong_list.h"
#include "mal_uoctet_list.h"
#include "mal_updateheader.h"
#include "mal_updateheader_list.h"
#include "mal_updatetype_list.h"
#include "mal_uri_list.h"
#include "mal_ushort_list.h"

#ifdef MAL_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C"
{
#endif

  //  Self test for private classes
  MAL_EXPORT void mal_private_selftest(bool verbose, const char* subtest);

#ifdef __cplusplus
}
#endif
#endif // MAL_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
